# -*- coding: utf-8 -*-
"""Rishaw_Titanic_Survivors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTYOCv52LlQDNPRaIkgoPy8_mb5k3mcj
"""

import pandas as pd
import numpy as np

"""We use pandas read_csv function to read the csv file in python and pandas DataFrame method to convert file into the data frame."""

df=pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

df.shape

df.isnull().sum()

"""Seperating out the columns which have more than 35% of the values missing in the dataset"""

#df.isnull().sum() returns a pandas series with columns name as the label index
#and total count of null values in the column as it's value
#And we are storing only those columns which have more than 35% of the data missing.

x=df.isnull().sum()
drop_col = x[x>(35/100 * df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()

df.fillna(df.mean(), inplace = True)
df.isnull().sum()

"""Because Embarked contains string values, we see the details of that column seperately from others as strings does not have mean and all. """

df['Embarked'].describe()

"""For Embarked attribute, we fill the NULL values with the most frequent value in the column."""

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum() ##NOW ALL THE NULL VALUES HAVE BEEN FILLED

df.corr()

"""sibsp: Number of Siblings/Spouses Abroad

parch: Number of Parents/Children Abroad

So we can make a new column family_size by combining these two columns
"""

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'], axis=1, inplace=True)
df.corr()

"""Let's check if we whether the person was alone or not can affect the survival rate."""

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

"""If the person is alone he/she has less chance of surviving."""

df[['Alone','Fare']].corr()

"""So we can see if the person was not alone, the chance the ticket price is higher is high."""

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index] # 1 for female,0 for male
df.groupby(['Sex'])['Survived'].mean()

"""It shows, female passenger have more chance of surviving than male ones.

It shows women were prioritized over men.
"""

df.groupby(['Embarked'])['Survived'].mean()

"""CONCLUSION

•	Female passengers were prioritized over men.

•	People with high class or rich people have higher survival rate than others. The hierarchy might have been followed while saving the passengers.

•	Passengers travelling with their family have higher survival rate.

•	Passengers who boarded the ship at Cherbourg, survived more in proportion than the others.

"""